import { motion } from 'framer-motion';
import { Brain } from 'lucide-react';

export default function ExecutiveSummary({ text }) {
  if (!text) return null;

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.3, duration: 0.4 }}
      className="bg-bg-card border border-border rounded-xl p-6 hover:scale-[1.01] transition-transform duration-200"
    >
      <div className="flex items-center gap-3 mb-4">
        <div className="w-9 h-9 rounded-lg bg-purple/20 flex items-center justify-center">
          <Brain className="w-5 h-5 text-purple" />
        </div>
        <div>
          <h3 className="font-display text-text font-medium">Executive Summary</h3>
          <span className="text-xs text-muted font-mono">Generated by Groq LLM</span>
        </div>
      </div>
      <p className="text-sm text-text/85 leading-relaxed font-display">{text}</p>
    </motion.div>
  );
}
